sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Cs079366!
  alioss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    bucket-name: web-tlias-26
    access-key-secret: Nc8iBrKAizFFNK8IqW1eLmQOqH6tnu
    access-key-id: LTAI5tE5LqBXmR3XdwhirZH2
