sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Cs079366!
  alioss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    bucket-name: web-tlias-26
    access-key-secret: YG6xtYUNDLbe7HsdCzKhevhDG2duGW
    access-key-id: LTAI5tMjegrBVsKS6Hd3EiTa
  redis:
    host: localhost
    port: 6379
    database: 2
  wechat:
    appid: wx95d7300561c4b602
    secret: 7f3062b155332c7dc2729c7b28a2c110
